# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxC2avyfGBExCTcH1yAwnpcLj0ra9CAg
"""

import setuptools

from os import path
this_directory = path.abspath(path.dirname(__file__))
with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()

setuptools.setup(
    name='cs107-4thPrime',
    version='0.0.1',
    author='Sirui Hu, Xiwen Jia, Jason Friedman, Robert Shekoyan',
    author_email=" ",
    description='Python Package for Automatic Differentiation',
    long_description=long_description,
    long_description_content_type='text/markdown',
    packages=setuptools.find_packages(),
    keywords=['Python','Automatic differentiation'],
    url='https://github.com/cs107-4thPrime/cs107-FinalProject',
    license='MIT',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
    ],
)